import 'package:flutter/material.dart';
import 'appColors.dart' as appColors;

const TextTheme TEXT_THEME_DEFAULT = TextTheme(
    headline1: TextStyle(
        color: appColors.COLOR_BLACK,
        fontWeight: FontWeight.w700,
        fontSize: 26),
    headline2: TextStyle(
        color: appColors.COLOR_BLACK,
        fontWeight: FontWeight.w700,
        fontSize: 22),
    headline3: TextStyle(
        color: appColors.COLOR_BLACK,
        fontWeight: FontWeight.w700,
        fontSize: 20),
    headline4: TextStyle(
        color: appColors.COLOR_BLACK,
        fontWeight: FontWeight.w700,
        fontSize: 16),
    headline5: TextStyle(
        color: appColors.COLOR_BLACK,
        fontWeight: FontWeight.w700,
        fontSize: 14),
    headline6: TextStyle(
        color: appColors.COLOR_BLACK,
        fontWeight: FontWeight.w700,
        fontSize: 12),
    bodyText1: TextStyle(
        color: appColors.COLOR_BLACK,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        height: 1.5),
    bodyText2: TextStyle(
        color: appColors.COLOR_GREY,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        height: 1.5),
    subtitle1: TextStyle(
        color: appColors.COLOR_BLACK,
        fontSize: 12,
        fontWeight: FontWeight.w400),
    subtitle2: TextStyle(
        color: appColors.COLOR_GREY,
        fontSize: 12,
        fontWeight: FontWeight.w400));
