version: '3.3'

services:
  mariadb:
    image: mariadb:10.6.4
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_fuelopt
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
