# Generated by Django 3.2.8 on 2021-11-17 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=12)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_wash', models.IntegerField(default=0)),
                ('air_and_water', models.IntegerField(default=0)),
                ('car_vacuum', models.IntegerField(default=0)),
                ('number_24_7_opening_hours', models.IntegerField(db_column='24_7_opening_hours')),
                ('toilet', models.IntegerField(default=0)),
                ('convenience_store', models.IntegerField(default=0)),
                ('atm', models.IntegerField(default=0)),
                ('parking_facilities', models.IntegerField(default=0)),
                ('disabled_toilet_baby_change', models.IntegerField(default=0)),
                ('alcohol', models.IntegerField(default=0)),
                ('wi_fi', models.IntegerField(default=0)),
                ('hgv_psv_fueling', models.IntegerField(default=0)),
                ('fuelservice', models.IntegerField(default=0)),
                ('payphone', models.IntegerField(default=0)),
                ('restaurant', models.IntegerField(default=0)),
                ('electric_car_charging', models.IntegerField(default=0)),
                ('repair_garage', models.IntegerField(default=0)),
                ('shower_facilities', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unleaded_price', models.DecimalField(decimal_places=1, default=None, max_digits=4, null=True)),
                ('diesel_price', models.DecimalField(decimal_places=1, default=None, max_digits=4, null=True)),
                ('super_unleaded_price', models.DecimalField(decimal_places=1, default=None, max_digits=4, null=True)),
                ('premium_diesel_price', models.DecimalField(decimal_places=1, default=None, max_digits=4, null=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('opening', models.BooleanField(null=True)),
                ('congestion', models.IntegerField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unleaded_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('diesel_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('super_unleaded_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('premium_diesel_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('unleaded_date', models.DateField(null=True)),
                ('diesel_date', models.DateField(null=True)),
                ('super_unleaded_date', models.DateField(null=True)),
                ('premium_diesel_date', models.DateField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
    ]
