# Generated by Django 3.2.8 on 2021-10-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='station',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='station',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='station',
            name='location',
            field=models.CharField(default='Default', max_length=200),
        ),
    ]
