# Generated by Django 3.2.9 on 2021-11-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unleaded_price', models.DecimalField(decimal_places=1, default=None, max_digits=4, null=True)),
                ('diesel_price', models.DecimalField(decimal_places=1, default=None, max_digits=4, null=True)),
                ('super_unleaded_price', models.DecimalField(decimal_places=1, default=None, max_digits=4, null=True)),
                ('premium_diesel_price', models.DecimalField(decimal_places=1, default=None, max_digits=4, null=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('opening', models.BooleanField(null=True)),
                ('congestion', models.IntegerField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
    ]
