# Generated by Django 3.2.9 on 2021-11-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelprice',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'managed': False},
        ),
    ]
