# Generated by Django 3.2.9 on 2021-11-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20211110_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelprice',
            options={},
        ),
        migrations.AlterModelTable(
            name='station',
            table='stations_station',
        ),
    ]
