# Generated by Django 3.2.8 on 2021-11-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_userreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelprice',
            name='diesel_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='premium_diesel_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='super_unleaded_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='unleaded_date',
            field=models.DateField(null=True),
        ),
    ]
