# Generated by Django 3.2.8 on 2021-10-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_auto_20211027_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelprice',
            old_name='premium_unleaded_date',
            new_name='premium_diesel_date',
        ),
        migrations.RenameField(
            model_name='fuelprice',
            old_name='premium_unleaded_price',
            new_name='premium_diesel_price',
        ),
    ]
