AWS_ACCESS_KEY_ID = "ADD YOUR ACCESS KEY ID HERE",
AWS_SECRET_ACCESS_KEY = "ADD YOUR SECRET ACCESS KEY HERE",

LOCATION_IQ_KEY = "ADD LOCATION_IQ_KEY"

KEY_1 = "ADD FIRST BING KEY HERE"
KEY_2 = "ADD SECOND BING KEY HERE"
