# Generated by Django 3.2.8 on 2021-12-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='congestion',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='opening',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
